# Generated by Django 5.1.6 on 2025-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ingredient_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prepared_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
