# Generated by Django 5.1.6 on 2025-04-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_prepared_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='api.recipe'),
        ),
    ]
